baseURL = 'http://berrig-analysis.com/'
languageCode = 'en-us'
title = 'Berrig Analysis'
author = "Christian Berrig"
DefaultContentLanguage = "en"
# defaultContentLanguageInSubdir = false
# enableInlineShortcodes = true
theme = "hyde"
enableRobotsTXT = true

[params]
    description = "Consultancy and solutions for system simulation and Bayesian data analysis"
    # description = "Offers consultancy and solutions to simulations of systems in economics, physics, mathematics, epidemiology and biology. We also offer statistical analysis of data using methods from Bayesian statistics."

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        # weight = 1

    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        # weight = 4

    [[menu.main]]
        name = "Github"
        url = "https://github.com/Berrig-Analysis"
        # pre = "<i class='icon-github text-2xl'></i>"
        # weight = 2

# [menu]
# 
#   [[menu.main]]
#     identifier = "products"
#     name = "Products"
#     url = "/products/"
#     weight = 1
# 
#   [[menu.main]]
#     identifier = "blog"
#     name = "Blog"
#     url = "/blog/"
#     weight = 2
# 
#   # Footer Menu
#   [[menu.footer]]
#     name = "Home"
#     url = "/"
#       weight = 1
# 
