baseURL = 'http://berrig-analysis.com/'
languageCode = 'en-us'
title = 'Berrig Analysis'
author = "Christian Berrig"
DefaultContentLanguage = "en"
# defaultContentLanguageInSubdir = false
# enableInlineShortcodes = true
theme = "hyde"
enableRobotsTXT = true

[params]
    description = "Consultancy and solutions for system simulation and Bayesian data analysis"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        # weight = 1

    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        # weight = 4

    [[menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/Berrig-Analysis"
        # pre = "<i class='icon-github text-2xl'></i>"
        # weight = 2

[caches]
    [caches.images]
        dir = ':cacheDir/images'

#   # Footer Menu
#   [[menu.footer]]
#     name = "Home"
#     url = "/"
#       weight = 1
# 
